"""
Danish-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'giv agt': 'attention', 'pas på': 'caution', 'kode': 'code', 'kode-blok': 'code', 'kildekode': 'code', 'fare': 'danger', 'fejl': 'error', 'vink': 'hint', 'vigtigt': 'important', 'bemærk': 'note', 'tips': 'tip', 'advarsel': 'warning', 'varsel': 'admonition', 'sidebjælke': 'sidebar', 'emne': 'topic', 'linje-blok': 'line-block', 'linie-blok': 'line-block', 'parset-literal': 'parsed-literal', 'rubrik': 'rubric', 'epigraf': 'epigraph', 'fremhævninger': 'highlights', 'pull-quote (translation required)': 'pull-quote', 'compound (translation required)': 'compound', 'container (translation required)': 'container', 'tabel': 'table', 'csv-tabel': 'csv-table', 'liste-tabel': 'list-table', 'meta': 'meta', 'math (translation required)': 'math', 'billede': 'image', 'figur': 'figure', 'inkludér': 'include', 'inkluder': 'include', 'rå': 'raw', 'erstat': 'replace', 'unicode': 'unicode', 'dato': 'date', 'klasse': 'class', 'rolle': 'role', 'forvalgt-rolle': 'default-role', 'titel': 'title', 'indhold': 'contents', 'sektnum': 'sectnum', 'sektions-nummerering': 'sectnum', 'sidehovede': 'header', 'sidefod': 'footer', 'target-notes (translation required)': 'target-notes', 'restructuredtext-test-direktiv': 'restructuredtext-test-directive'}
'Danish name to registered (in directives/__init__.py) directive name\nmapping.'
roles = {'forkortelse': 'abbreviation', 'fork': 'abbreviation', 'akronym': 'acronym', 'ac (translation required)': 'acronym', 'kode': 'code', 'indeks': 'index', 'i': 'index', 'subscript (translation required)': 'subscript', 'sub (translation required)': 'subscript', 'superscript (translation required)': 'superscript', 'sup (translation required)': 'superscript', 'titel-reference': 'title-reference', 'titel': 'title-reference', 't': 'title-reference', 'pep-reference': 'pep-reference', 'pep': 'pep-reference', 'rfc-reference': 'rfc-reference', 'rfc': 'rfc-reference', 'emfase': 'emphasis', 'kraftig': 'strong', 'literal': 'literal', 'math (translation required)': 'math', 'navngivet-reference': 'named-reference', 'anonym-reference': 'anonymous-reference', 'fodnote-reference': 'footnote-reference', 'citation-reference (translation required)': 'citation-reference', 'substitutions-reference': 'substitution-reference', 'target (translation required)': 'target', 'uri-reference': 'uri-reference', 'uri': 'uri-reference', 'url': 'uri-reference', 'rå': 'raw'}
'Mapping of Danish role names to canonical role names for interpreted text.\n'

