"""
Finnish-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'admonition (translation required)': 'admonition', 'huomio': 'attention', 'varo': 'caution', 'code (translation required)': 'code', 'vaara': 'danger', 'virhe': 'error', 'vihje': 'hint', 'tärkeää': 'important', 'huomautus': 'note', 'neuvo': 'tip', 'varoitus': 'warning', 'sivupalkki': 'sidebar', 'aihe': 'topic', 'rivi': 'line-block', 'tasalevyinen': 'parsed-literal', 'ohje': 'rubric', 'epigraafi': 'epigraph', 'kohokohdat': 'highlights', 'lainaus': 'pull-quote', 'taulukko': 'table', 'csv-taulukko': 'csv-table', 'list-table (translation required)': 'list-table', 'compound (translation required)': 'compound', 'container (translation required)': 'container', 'meta': 'meta', 'math (translation required)': 'math', 'kuva': 'image', 'kaavio': 'figure', 'sisällytä': 'include', 'raaka': 'raw', 'korvaa': 'replace', 'unicode': 'unicode', 'päiväys': 'date', 'luokka': 'class', 'rooli': 'role', 'default-role (translation required)': 'default-role', 'title (translation required)': 'title', 'sisällys': 'contents', 'kappale': 'sectnum', 'header (translation required)': 'header', 'footer (translation required)': 'footer', 'target-notes (translation required)': 'target-notes'}
'Finnish name to registered (in directives/__init__.py) directive name\nmapping.'
roles = {'lyhennys': 'abbreviation', 'akronyymi': 'acronym', 'kirjainsana': 'acronym', 'code (translation required)': 'code', 'hakemisto': 'index', 'luettelo': 'index', 'alaindeksi': 'subscript', 'indeksi': 'subscript', 'yläindeksi': 'superscript', 'title-reference (translation required)': 'title-reference', 'title (translation required)': 'title-reference', 'pep-reference (translation required)': 'pep-reference', 'rfc-reference (translation required)': 'rfc-reference', 'korostus': 'emphasis', 'vahvistus': 'strong', 'tasalevyinen': 'literal', 'math (translation required)': 'math', 'named-reference (translation required)': 'named-reference', 'anonymous-reference (translation required)': 'anonymous-reference', 'footnote-reference (translation required)': 'footnote-reference', 'citation-reference (translation required)': 'citation-reference', 'substitution-reference (translation required)': 'substitution-reference', 'kohde': 'target', 'uri-reference (translation required)': 'uri-reference', 'raw (translation required)': 'raw'}
'Mapping of Finnish role names to canonical role names for interpreted text.\n'

