"""
French-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'attention': 'attention', 'précaution': 'caution', 'danger': 'danger', 'erreur': 'error', 'conseil': 'hint', 'important': 'important', 'note': 'note', 'astuce': 'tip', 'avertissement': 'warning', 'annonce': 'admonition', 'encadré': 'sidebar', 'sujet': 'topic', 'bloc-textuel': 'line-block', 'bloc-interprété': 'parsed-literal', 'code-interprété': 'parsed-literal', 'code': 'code', 'math (translation required)': 'math', 'intertitre': 'rubric', 'exergue': 'epigraph', 'épigraphe': 'epigraph', 'chapeau': 'highlights', 'accroche': 'pull-quote', 'compound (translation required)': 'compound', 'container (translation required)': 'container', 'tableau': 'table', 'csv-table (translation required)': 'csv-table', 'list-table (translation required)': 'list-table', 'méta': 'meta', 'image': 'image', 'figure': 'figure', 'inclure': 'include', 'brut': 'raw', 'remplacer': 'replace', 'remplace': 'replace', 'unicode': 'unicode', 'date': 'date', 'classe': 'class', 'role (translation required)': 'role', 'default-role (translation required)': 'default-role', 'titre (translation required)': 'title', 'sommaire': 'contents', 'table-des-matières': 'contents', 'sectnum': 'sectnum', 'section-numérotée': 'sectnum', 'liens': 'target-notes', 'header (translation required)': 'header', 'footer (translation required)': 'footer'}
'Mapping of French directive names to registered directive names\n\nCf. https://docutils.sourceforge.io/docs/ref/rst/directives.html\nand `_directive_registry` in ``directives/__init__.py``.\n'
roles = {'abréviation': 'abbreviation', 'acronyme': 'acronym', 'sigle': 'acronym', 'code': 'code', 'emphase': 'emphasis', 'littéral': 'literal', 'math (translation required)': 'math', 'pep-référence': 'pep-reference', 'rfc-référence': 'rfc-reference', 'fort': 'strong', 'indice': 'subscript', 'ind': 'subscript', 'exposant': 'superscript', 'exp': 'superscript', 'titre-référence': 'title-reference', 'titre': 'title-reference', 'brut': 'raw', 'index': 'index', 'nommée-référence': 'named-reference', 'anonyme-référence': 'anonymous-reference', 'note-référence': 'footnote-reference', 'citation-référence': 'citation-reference', 'substitution-référence': 'substitution-reference', 'lien': 'target', 'uri-référence': 'uri-reference'}
'Mapping of French role names to canonical role names for interpreted text.\n'

