"""
Slovak-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'pozor': 'attention', 'opatrne': 'caution', 'code (translation required)': 'code', 'nebezpeèenstvo': 'danger', 'chyba': 'error', 'rada': 'hint', 'dôle\x9eité': 'important', 'poznámka': 'note', 'tip (translation required)': 'tip', 'varovanie': 'warning', 'admonition (translation required)': 'admonition', 'sidebar (translation required)': 'sidebar', 'téma': 'topic', 'blok-riadkov': 'line-block', 'parsed-literal': 'parsed-literal', 'rubric (translation required)': 'rubric', 'epigraph (translation required)': 'epigraph', 'highlights (translation required)': 'highlights', 'pull-quote (translation required)': 'pull-quote', 'compound (translation required)': 'compound', 'container (translation required)': 'container', 'table (translation required)': 'table', 'csv-table (translation required)': 'csv-table', 'list-table (translation required)': 'list-table', 'meta': 'meta', 'math (translation required)': 'math', 'obrázok': 'image', 'tvar': 'figure', 'vlo\x9ei\x9d': 'include', 'raw (translation required)': 'raw', 'nahradi\x9d': 'replace', 'unicode': 'unicode', 'dátum': 'date', 'class (translation required)': 'class', 'role (translation required)': 'role', 'default-role (translation required)': 'default-role', 'title (translation required)': 'title', 'obsah': 'contents', 'èas\x9d': 'sectnum', 'èas\x9d-èíslovanie': 'sectnum', 'cie¾ové-poznámky': 'target-notes', 'header (translation required)': 'header', 'footer (translation required)': 'footer'}
'Slovak name to registered (in directives/__init__.py) directive name\nmapping.'
roles = {'abbreviation (translation required)': 'abbreviation', 'acronym (translation required)': 'acronym', 'code (translation required)': 'code', 'index (translation required)': 'index', 'subscript (translation required)': 'subscript', 'superscript (translation required)': 'superscript', 'title-reference (translation required)': 'title-reference', 'pep-reference (translation required)': 'pep-reference', 'rfc-reference (translation required)': 'rfc-reference', 'emphasis (translation required)': 'emphasis', 'strong (translation required)': 'strong', 'literal (translation required)': 'literal', 'math (translation required)': 'math', 'named-reference (translation required)': 'named-reference', 'anonymous-reference (translation required)': 'anonymous-reference', 'footnote-reference (translation required)': 'footnote-reference', 'citation-reference (translation required)': 'citation-reference', 'substitution-reference (translation required)': 'substitution-reference', 'target (translation required)': 'target', 'uri-reference (translation required)': 'uri-reference', 'raw (translation required)': 'raw'}
'Mapping of Slovak role names to canonical role names for interpreted text.\n'

