"""
Latvian-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'uzmanību': 'attention', 'piesardzību': 'caution', 'kods': 'code', 'koda-bloks': 'code', 'pirmkods': 'code', 'bīstami': 'danger', 'kļūda': 'error', 'ieteikums': 'hint', 'svarīgi': 'important', 'piezīme': 'note', 'padoms': 'tip', 'brīdinājums': 'warning', 'aizrādījums': 'admonition', 'sānjosla': 'sidebar', 'tēma': 'topic', 'rindu-bloks': 'line-block', 'parsēts-literālis': 'parsed-literal', 'rubrika': 'rubric', 'epigrāfs': 'epigraph', 'apskats': 'highlights', 'izvilkuma-citāts': 'pull-quote', 'savienojums': 'compound', 'konteiners': 'container', 'tabula': 'table', 'csv-tabula': 'csv-table', 'sarakstveida-tabula': 'list-table', 'meta': 'meta', 'matemātika': 'math', 'attēls': 'image', 'figūra': 'figure', 'ietvert': 'include', 'burtiski': 'raw', 'aizvieto': 'replace', 'unicode': 'unicode', 'datums': 'date', 'klase': 'class', 'role': 'role', 'noklusējuma-role': 'default-role', 'virsraksts': 'title', 'saturs': 'contents', 'numurēt-sekcijas': 'sectnum', 'galvene': 'header', 'kājene': 'footer', 'atsauces-apakšā': 'target-notes', 'restructuredtext-testa-direktīva': 'restructuredtext-test-directive'}
'English name to registered (in directives/__init__.py) directive name\nmapping.'
roles = {'saīsinājums': 'abbreviation', 'īsi': 'abbreviation', 'akronīms': 'acronym', 'kods': 'code', 'indekss': 'index', 'i': 'index', 'apakšraksts': 'subscript', 'apakšā': 'subscript', 'augšraksts': 'superscript', 'augšā': 'superscript', 'virsraksta-atsauce': 'title-reference', 'virsraksts': 'title-reference', 'v': 'title-reference', 'atsauce-uz-pep': 'pep-reference', 'pep': 'pep-reference', 'atsauce-uz-rfc': 'rfc-reference', 'rfc': 'rfc-reference', 'izcēlums': 'emphasis', 'blīvs': 'strong', 'literālis': 'literal', 'matemātika': 'math', 'nosaukta-atsauce': 'named-reference', 'nenosaukta-atsauce': 'anonymous-reference', 'kājenes-atsauce': 'footnote-reference', 'citātā-atsauce': 'citation-reference', 'aizvietojuma-atsauce': 'substitution-reference', 'mērkis': 'target', 'atsauce-uz-uri': 'uri-reference', 'uri': 'uri-reference', 'url': 'uri-reference', 'burtiski': 'raw'}
'Mapping of English role names to canonical role names for interpreted text.\n'

