"""
Dutch-language mappings for language-dependent features of
reStructuredText.
"""

__docformat__ = 'reStructuredText'
directives = {'attentie': 'attention', 'let-op': 'caution', 'code (translation required)': 'code', 'gevaar': 'danger', 'fout': 'error', 'hint': 'hint', 'belangrijk': 'important', 'opmerking': 'note', 'tip': 'tip', 'waarschuwing': 'warning', 'advies': 'admonition', 'katern': 'sidebar', 'onderwerp': 'topic', 'lijn-blok': 'line-block', 'letterlijk-ontleed': 'parsed-literal', 'rubriek': 'rubric', 'opschrift': 'epigraph', 'hoogtepunten': 'highlights', 'pull-quote': 'pull-quote', 'samenstelling': 'compound', 'verbinding': 'compound', 'container (translation required)': 'container', 'tabel': 'table', 'csv-tabel': 'csv-table', 'lijst-tabel': 'list-table', 'meta': 'meta', 'math (translation required)': 'math', 'beeld': 'image', 'figuur': 'figure', 'opnemen': 'include', 'onbewerkt': 'raw', 'vervang': 'replace', 'vervanging': 'replace', 'unicode': 'unicode', 'datum': 'date', 'klasse': 'class', 'rol': 'role', 'default-role (translation required)': 'default-role', 'title (translation required)': 'title', 'inhoud': 'contents', 'sectnum': 'sectnum', 'sectie-nummering': 'sectnum', 'hoofdstuk-nummering': 'sectnum', 'header (translation required)': 'header', 'footer (translation required)': 'footer', 'verwijzing-voetnoten': 'target-notes', 'restructuredtext-test-instructie': 'restructuredtext-test-directive'}
'Dutch name to registered (in directives/__init__.py) directive name\nmapping.'
roles = {'afkorting': 'abbreviation', 'acroniem': 'acronym', 'ac': 'acronym', 'code (translation required)': 'code', 'index': 'index', 'i': 'index', 'inferieur': 'subscript', 'inf': 'subscript', 'superieur': 'superscript', 'sup': 'superscript', 'titel-referentie': 'title-reference', 'titel': 'title-reference', 't': 'title-reference', 'pep-referentie': 'pep-reference', 'pep': 'pep-reference', 'rfc-referentie': 'rfc-reference', 'rfc': 'rfc-reference', 'nadruk': 'emphasis', 'extra': 'strong', 'extra-nadruk': 'strong', 'vet': 'strong', 'letterlijk': 'literal', 'math (translation required)': 'math', 'benoemde-referentie': 'named-reference', 'anonieme-referentie': 'anonymous-reference', 'voetnoot-referentie': 'footnote-reference', 'citaat-referentie': 'citation-reference', 'substitie-reference': 'substitution-reference', 'verwijzing': 'target', 'uri-referentie': 'uri-reference', 'uri': 'uri-reference', 'url': 'uri-reference', 'onbewerkt': 'raw'}
'Mapping of Dutch role names to canonical role names for interpreted text.\n'

